import pyodbc
import os

class mainConnection:

    # read-only attributes
    __DEFAULT_DATABASE: str

    def get(self, sql: str, *params): ...
    def execute(self, sql: str, *params) -> None: ...
    def addLinkedAccount(self, twitchID, discordID) -> None: ...
    def getAccounts(self): ...